### ISSUE TITLE
Structuring the author affiliations in YAML and Template txt file

### ISSUE THREAD

**Issue by rccline** [rccline/physalia-repo-latex#3]
Let's say there are four authors:  How would you complete this?
% \affiliation{1}{First Affiliation}
% \affiliation{2}{Second Affiliation}
% \affiliation{3}{Third Affiliation}
% \affiliation{4}{Fourth Affiliation}
\affiliation{=number=}{=Affiliation Address=}
%(repeat as many times as is necessary)

**Comment by rccline** [comment]
Elio writes:  For personal use, the easiest way would be to hardcode it. Use
affilation1: first affilation
affiliation2: scond affiliation
 and so on in the yaml and
\affiliation{1}{$affiliation1$}
\affiliation{2}{$affiliation2$}
in the template.  

However, this solution threw an error.

**Comment by rccline** [comment]
o generalise to arbitrary number of affiliations you need to use more advanced pandoc template syntax.
You can put something like
```
affiliations:
   - number: 1
     affiliation: First affiliation
   - number: 2
     affiliation: Second Affiliation
```
